# Import the required libraries
import streamlit as st
import pandas as pd
import joblib

# Load the saved files
model = joblib.load('model_heart_disease_predictor.pkl')
scaler = joblib.load('scaler_heart_disease_predictor.pkl')
columns = joblib.load('columns_heart_disease_predictor.pkl')

# Display the title and instructions
st.title('Heart Disease Prediction')
st.markdown("Please provide the patient's clinical information below to predict the risk of heart disease.")

# Collect User Input
age = st.slider('Age', 0, 100, 20)
sex = st.selectbox('Sex', ['M', 'F'])
chest_pain = st.selectbox('Chest Pain Type', ['ATA', 'NAP', 'TA', 'ASY'])
resting_bp = st.number_input('Resting Blood Pressure (mm Hg)', 0, 500, 0)
cholesterol = st.number_input('Cholesterol (mg/dL)', 0, 500, 0)
fasting_bs = st.selectbox('Fasting Blood Sugar > 120 mg/dL', [0, 1])
resting_ecg = st.selectbox('Resting ECG', ['Normal', 'ST', 'LVH'])
max_hr = st.slider('Max Heart Rate', 0, 500, 0)
exercise_angina = st.selectbox('Exercise-Induced Angina', ['Y', 'N'])
oldpeak = st.slider('Oldpeak (ST Depression)', 0.0, 10.0, 0.0)
st_slope = st.selectbox('ST Slope', ['Up', 'Flat', 'Down'])

# Make the prediction and show the result
if st.button("Predict"):
    raw_input = {'Age': age, 'RestingBP': resting_bp, 'Cholesterol': cholesterol, 'FastingBS': fasting_bs,
                 'MaxHR': max_hr, 'Oldpeak': oldpeak, 'Sex_'+sex: 1, 'ChestPainType_'+chest_pain: 1,
                 'RestingECG_'+resting_ecg: 1, 'ExerciseAngina_'+exercise_angina: 1, 'ST_Slope_'+st_slope: 1}
    input_df = pd.DataFrame([raw_input])
    for col in columns:
        if col not in input_df.columns:
            input_df[col] = 0
    input_df = input_df[columns]
    
    numerical_cols = ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']
    input_df[numerical_cols] = scaler.transform(input_df[numerical_cols])
    
    prediction = model.predict(input_df)[0]
    if prediction == 1:
        st.error("⚠️ High Risk of Heart Disease")
    else:
        st.success("✅ Low Risk of Heart Disease")

st.markdown("---")
st.caption(
    "Disclaimer: This application is intended for educational purposes only. "
    "Predictions are generated by a machine learning model and should not be used as a substitute for professional medical advice.")